apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: backend-python-boilerplate
    context: .
    sync:
      manual:
        - src: "**"
          dest: "/src"
deploy:
  kubectl:
    manifests:
      - skaffold/*.yaml
